# Generated by Django 2.2.1 on 2019-08-06 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190805_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedetails',
            name='description_fr',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moviedetails',
            name='title_fr',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
